## Tutorial 1

This tutorial has been created to help students that have not experience in **Python**, **Numpy** and **OpenCV**. However, we expect that you have some experience coding in any other programming language. In that matter It is expected that some of you may have previous knowledge in **Matlab**, in which case we recommend to take a look of the **Numpy** for Matlab users page http://wiki.scipy.org/NumPy_for_Matlab_Users.

In this tutorial, we will cover:
* Basic Python: data types, functions, classes, control flow.
* Numpy: Array, Array indexing, Datatypes, vector, matrix.
* IPython: Notebooks.
* Opencv: I/O video and images.
* Matplotlib: plotting, subplotings and images.


### Python

Wiki description * **Python** is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991.*

Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable

It is important to notice that there are currently two different supported versions of Python, 2.7 and 3.5. Python 3 introduced many backwards-incompatible changes to the language, so code written for 2.7 may not work under 3.5 and vice versa.

### Basic data types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

**Numbers** https://docs.python.org/3.5/library/stdtypes.html#numeric-types-int-float-complex Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

**Boolean** https://docs.python.org/3.5/library/stdtypes.html#boolean-operations-and-or-not Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.) 

**Strings** https://docs.python.org/3.5/library/stdtypes.html#string-methods

In [ ]:
## Numbers ##

x = 3
print('Type {}'.format(type(x)))
print('x = {}'.format(x))
print('x + 1  = {}'.format(x + 1))
print('x - 1  = {}'.format(x - 1))
print('x * 2  = {}'.format(x * 2))
print('x ** 2 = {}'.format(x ** 2)) 

x += 1
print('x = {}'.format(x))

x *= 2
print('x = {}'.format(x))

y = 2.5
print('Type {}'.format(type(y)))
print(y, y + 1, y * 2, y ** 2)

In [ ]:
## Booleans
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

In [ ]:
## Strings 
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

### Indentation [Warning]

In Python there are **NO brakets** or **end** keywords to close a block of code that is inside a flow control instruction. You need to **properly indent** your code, as it is the only mechanism to indicate the nesting of intructions.

Indentation is achieved by inserting **4 spaces** on the left side of each line that belong to a block. This will help (force) you to write **neat, clear and easy to read** code.

### Containers

**Lists** https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

**Dictionaries** https://docs.python.org/3.5/library/stdtypes.html#dict A dictionary stores (key, value) pairs, similar to a Map in Java.

**Sets** https://docs.python.org/3.5/library/stdtypes.html#set

**Tuples** https://docs.python.org/3.5/tutorial/datastructures.html#tuples-and-sequences


In [ ]:
## Lists
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"

In [ ]:
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"

In [ ]:
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

In [ ]:
## Slicing
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

In [ ]:
## Dictionaries 
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

In [ ]:
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

In [ ]:
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

### Functions and Classes


Python functions are defined using the **def** keyword. For example:

In [ ]:
def sign(x, y=0):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

The syntax for defining classes in Python is straightforward

In [ ]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

### Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

To use Numpy, we first need to import the numpy package:

In [ ]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create an array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              

In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              

In [ ]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               

In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)                             

In [ ]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)      

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

### Comprehensive numpy usage
Describe the result/function of each of the following commands. Please utilize the inbuilt help() command if you are unfamiliar with the these functions. 

In [ ]:
a = np.array([[1, 2, 3], [5, 2, 20]])
b = a[1, :]
f = np.random.rand(200, 1)
g = f[f > 0]
x = np.zeros(50) + 0.5
y = 0.5 * np.ones([1, len(x)])
z = x + y
a = np.linspace(1, 200)
b = a[::-1]
b[b < 35] = 0

### Matplotlib

Matplotlib is a plotting library. In this section give a brief introduction to the matplotlib.pyplot module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

### Image processing

In [ ]:
import numpy as np
import imageio.v2 as imageio
# from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img = imageio.imread('Lenna.png')
img_tinted = img * [1, 0.95, 0.9]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_tinted))
plt.show()

In [ ]:
img = imageio.imread('Lenna.png')
imgGray = img[:,:,0] * 0.299 + img[:,:,1]*0.587 + img[:,:,2] * 0.114
imgGray = np.dot(img[:,:,:3], [0.299, 0.587, 0.114])
# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(imgGray,cmap='gray')
plt.show()

In [ ]:
img = imageio.imread('Lenna.png')
r = 240; c = 235;
w = 150; h = 50;
imgCrop = img[r : r + h, c : c + w, :]
plt.imshow(imgCrop);

In [ ]:
imgThreshold = imgGray.copy()
rows, cols = imgThreshold.shape
print('width :{}, height :{}'.format(cols,rows))
for c in range(cols):
    for r in range(rows):
        if imgThreshold[r,c] > 125:
            imgThreshold[r,c] = 1
        else:
            imgThreshold[r,c] = 0

plt.imshow(imgThreshold,cmap='gray')

In [ ]:
imgThreshold = imgGray.copy()
imgThreshold[imgThreshold > 125] = 255.
imgThreshold[imgThreshold <= 125] = 0.
imgThreshold = imgThreshold/255
plt.imshow(imgThreshold/255,cmap='gray')

## Morphology operations

http://scikit-image.org/docs/dev/api/skimage.morphology.html

In [ ]:
from skimage.morphology import erosion, square


selem = square(3);
eroded = erosion(imgThreshold, selem)

plt.imshow(eroded, cmap='gray')

In [ ]:
from skimage.morphology import dilation, square

result = dilation(imgThreshold,square(3))
plt.imshow(result,cmap='gray')

## Geometric Transformations of Images
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_geometric_transformations/py_geometric_transformations.html

In [ ]:
from skimage.transform import warp
from skimage.transform import SimilarityTransform
tform = SimilarityTransform(translation=(-100, -50))
warped = warp(img, tform)
plt.imshow(warped)

In [ ]:
tform = SimilarityTransform(rotation=0.2)
warped = warp(img, tform)
plt.imshow(warped)